"""initial schema — all P1 tables.

Autogenerated against the SQLAlchemy models, then hand-adjusted:
- CREATE EXTENSION citext / pg_trgm up front
- `messages` and `events` are created via raw SQL as monthly
  RANGE-partitioned tables (PK includes the partition key) with a DEFAULT
  partition so writes never fail before pg_partman is configured.
  PRODUCTION NOTE: attach pg_partman (or the beat month-roller) to create
  monthly children ahead of time; retention = plan history via partition
  drops (13 months for events).
- trigram GIN index on messages.text_plain (134-language search).

Revision ID: 0001
Revises:
Create Date: 2026-07-07 17:33:09.585781
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('price_usd_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('translation_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('src_lang', sa.String(length=16), nullable=True),
    sa.Column('dst_lang', sa.String(length=16), nullable=False),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('data_key_enc', postgresql.BYTEA(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_points_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_points_ledger_ws_created', 'ai_points_ledger', ['workspace_id', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_ws_created', 'audit_logs', ['workspace_id', 'created_at'], unique=False)
    op.create_table('channel_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('credentials_enc', postgresql.BYTEA(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('webhook_secret', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("channel_type IN ('widget','telegram_bot','telegram_app','email','messenger','instagram','whatsapp_cloud','whatsapp_app','line_oa','line_app','wechat','wecom','wechat_kf','tiktok','tiktok_business','youtube','zalo_app','slack','vk','sms')", name='ck_channel_accounts_type'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_type', 'external_id', name='uq_channel_accounts_type_ext')
    )
    op.create_index(op.f('ix_channel_accounts_workspace_id'), 'channel_accounts', ['workspace_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('remark_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('custom', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_custom_gin', 'contacts', ['custom'], unique=False, postgresql_using='gin')
    op.create_index('ix_contacts_ws_email', 'contacts', ['workspace_id', 'email'], unique=False)
    op.create_index('ix_contacts_ws_last_seen', 'contacts', ['workspace_id', 'last_seen_at'], unique=False)
    op.create_index('ix_contacts_ws_phone', 'contacts', ['workspace_id', 'phone'], unique=False)
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('entity', sa.String(length=16), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'entity', 'key', name='uq_custom_fields_ws_entity_key')
    )
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime', sa.String(length=128), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_by_type', sa.String(length=16), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'sha256', name='uq_files_ws_sha256')
    )
    op.create_table('llm_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key_enc', postgresql.BYTEA(), nullable=True),
    sa.Column('model_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_profiles_workspace_id'), 'llm_profiles', ['workspace_id'], unique=False)
    op.create_table('mac_activity',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'period_month', 'contact_id')
    )
    op.create_table('member_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_member_groups_ws_name')
    )
    op.create_table('message_dedup',
    sa.Column('channel_account_id', sa.UUID(), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_account_id', 'external_message_id')
    )
    op.create_table('message_translations',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('target_lang', sa.String(length=16), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('engine', sa.String(length=24), nullable=False),
    sa.Column('detected_source_lang', sa.String(length=16), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'target_lang')
    )
    op.create_index('ix_message_translations_ws', 'message_translations', ['workspace_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('role_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_roles_ws_name')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('plan_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'kind', 'name', name='uq_tags_ws_kind_name')
    )
    op.create_table('timers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timers_status_fire', 'timers', ['status', 'fire_at'], unique=False)
    op.create_index('ix_timers_ws_kind_ref', 'timers', ['workspace_id', 'kind', 'ref_id'], unique=False)
    op.create_table('usage_counters',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=48), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'metric', 'period_month')
    )
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('only_customer_messages', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_workspace_id'), 'webhook_subscriptions', ['workspace_id'], unique=False)
    op.create_table('channel_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_account_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=24), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('logged_in_external_id', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_account_id', 'external_user_id', name='uq_channel_identities_acct_ext')
    )
    op.create_index(op.f('ix_channel_identities_logged_in_external_id'), 'channel_identities', ['logged_in_external_id'], unique=False)
    op.create_index('ix_channel_identities_ws_contact', 'channel_identities', ['workspace_id', 'contact_id'], unique=False)
    op.create_table('contact_merge_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_a_id', sa.UUID(), nullable=False),
    sa.Column('contact_b_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contact_a_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_b_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'contact_a_id', 'contact_b_id', 'match_type', name='uq_merge_candidates_pair')
    )
    op.create_table('contact_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('store_platform', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('total', sa.String(length=32), nullable=True),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'store_platform', 'external_order_id', name='uq_contact_orders_ext')
    )
    op.create_index('ix_contact_orders_ws_contact', 'contact_orders', ['workspace_id', 'contact_id'], unique=False)
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_index(op.f('ix_contact_tags_workspace_id'), 'contact_tags', ['workspace_id'], unique=False)
    op.create_table('device_bridges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_account_id', sa.UUID(), nullable=False),
    sa.Column('bridge_type', sa.String(length=16), nullable=False),
    sa.Column('container_name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_blob_key', sa.Text(), nullable=True),
    sa.Column('proxy_url_enc', postgresql.BYTEA(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_account_id')
    )
    op.create_index(op.f('ix_device_bridges_workspace_id'), 'device_bridges', ['workspace_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_deliveries_retry', 'webhook_deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_index('ix_webhook_deliveries_ws_sub', 'webhook_deliveries', ['workspace_id', 'subscription_id', 'created_at'], unique=False)
    op.create_table('widgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_account_id', sa.UUID(), nullable=True),
    sa.Column('widget_key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_removed', sa.Boolean(), nullable=False),
    sa.Column('default_flow_id', sa.UUID(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('widget_key')
    )
    op.create_index(op.f('ix_widgets_workspace_id'), 'widgets', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('member_type', sa.String(length=16), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_concurrent', sa.Integer(), nullable=False),
    sa.Column('ai_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('invited_email', postgresql.CITEXT(), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index('uq_members_ws_user_notnull', 'workspace_members', ['workspace_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('api_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['workspace_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_api_tokens_workspace_id'), 'api_tokens', ['workspace_id'], unique=False)
    op.create_table('contact_merges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('target_contact_id', sa.UUID(), nullable=False),
    sa.Column('source_contact_id', sa.UUID(), nullable=False),
    sa.Column('moved_identity_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('moved_conversation_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_overwrites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('merged_by_member_id', sa.UUID(), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_by_member_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['merged_by_member_id'], ['workspace_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_merges_ws_target', 'contact_merges', ['workspace_id', 'target_contact_id'], unique=False)
    op.create_table('contact_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('author_member_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_member_id'], ['workspace_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_notes_ws_contact', 'contact_notes', ['workspace_id', 'contact_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('channel_identity_id', sa.UUID(), nullable=False),
    sa.Column('channel_account_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=24), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('handler', sa.String(length=16), nullable=False),
    sa.Column('assignee_member_id', sa.UUID(), nullable=True),
    sa.Column('bot_managed', sa.Boolean(), nullable=False),
    sa.Column('ai_state', sa.String(length=16), nullable=False),
    sa.Column('needs_reply', sa.Boolean(), nullable=False),
    sa.Column('agent_unread_count', sa.Integer(), nullable=False),
    sa.Column('customer_window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('translation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_agent_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_member_id'], ['workspace_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_account_id'], ['channel_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_identity_id'], ['channel_identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_identity_id')
    )
    op.create_index('ix_conversations_ws_assignee', 'conversations', ['workspace_id', 'assignee_member_id'], unique=False)
    op.create_index('ix_conversations_ws_contact', 'conversations', ['workspace_id', 'contact_id'], unique=False)
    op.create_index('ix_conversations_ws_needs_reply', 'conversations', ['workspace_id', 'needs_reply'], unique=False)
    op.create_index('ix_conversations_ws_status_last', 'conversations', ['workspace_id', 'status', 'last_message_at'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_member_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['workspace_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_workspace_id'), 'materials', ['workspace_id'], unique=False)
    op.create_table('member_daily_stats',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('handled_count', sa.Integer(), nullable=False),
    sa.Column('resolved_count', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('first_response_ms_sum', sa.BigInteger(), nullable=False),
    sa.Column('first_response_count', sa.Integer(), nullable=False),
    sa.Column('online_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'member_id', 'day')
    )
    op.create_table('member_group_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['member_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'member_id')
    )
    op.create_index(op.f('ix_member_group_members_workspace_id'), 'member_group_members', ['workspace_id'], unique=False)
    op.create_table('member_shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_min', sa.Integer(), nullable=False),
    sa.Column('end_min', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_shifts_ws_member', 'member_shifts', ['workspace_id', 'member_id'], unique=False)
    op.create_table('quick_reply_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('owner_member_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_reply_folders_workspace_id'), 'quick_reply_folders', ['workspace_id'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=8), nullable=False),
    sa.Column('owner_member_id', sa.UUID(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_views_workspace_id'), 'saved_views', ['workspace_id'], unique=False)
    op.create_table('visitor_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('channel_identity_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=24), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_identity_id'], ['channel_identities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visitor_events_ws_identity', 'visitor_events', ['workspace_id', 'channel_identity_id'], unique=False)
    op.create_index('ix_visitor_events_ws_occurred', 'visitor_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('conversation_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('from_handler', sa.String(length=16), nullable=True),
    sa.Column('from_member_id', sa.UUID(), nullable=True),
    sa.Column('to_handler', sa.String(length=16), nullable=False),
    sa.Column('to_member_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_assignments_ws_conv', 'conversation_assignments', ['workspace_id', 'conversation_id'], unique=False)
    op.create_table('conversation_reads',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('last_read_message_id', sa.UUID(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'member_id')
    )
    op.create_index('ix_conversation_reads_ws_member', 'conversation_reads', ['workspace_id', 'member_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_by', sa.String(length=16), nullable=False),
    sa.Column('closed_by_type', sa.String(length=16), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('handler_at_close', sa.String(length=16), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('contact_message_count', sa.Integer(), nullable=False),
    sa.Column('agent_message_count', sa.Integer(), nullable=False),
    sa.Column('csat_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_sessions_ws_conv', 'conversation_sessions', ['workspace_id', 'conversation_id'], unique=False)
    op.create_index('ix_conversation_sessions_ws_started', 'conversation_sessions', ['workspace_id', 'started_at'], unique=False)
    op.create_table('conversation_tags',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'tag_id')
    )
    op.create_index(op.f('ix_conversation_tags_workspace_id'), 'conversation_tags', ['workspace_id'], unique=False)
    op.create_table('quick_replies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('owner_member_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('shortcut', sa.String(length=32), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_plain', sa.Text(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['quick_reply_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_member_id'], ['workspace_members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quick_replies_ws_scope', 'quick_replies', ['workspace_id', 'scope'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # partitioned hot tables (raw SQL — see module docstring)
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE messages (
            id UUID NOT NULL,
            workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
            conversation_id UUID NOT NULL,
            channel_identity_id UUID,
            direction VARCHAR(3) NOT NULL,
            sender_type VARCHAR(16) NOT NULL,
            sender_id UUID,
            msg_type VARCHAR(24) NOT NULL DEFAULT 'text',
            content JSONB NOT NULL DEFAULT '{}'::jsonb,
            text_plain TEXT,
            is_note BOOLEAN NOT NULL DEFAULT false,
            sent_via VARCHAR(16),
            source_flow_id UUID,
            external_message_id VARCHAR(255),
            client_msg_id VARCHAR(64),
            delivery_status VARCHAR(12) NOT NULL DEFAULT 'pending',
            delivery_error TEXT,
            external_timestamp TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, created_at)
        ) PARTITION BY RANGE (created_at)
        """
    )
    op.execute("CREATE TABLE messages_default PARTITION OF messages DEFAULT")
    op.execute(
        "CREATE INDEX ix_messages_ws_conv_created ON messages (workspace_id, conversation_id, created_at)"
    )
    op.execute("CREATE INDEX ix_messages_conv_created ON messages (conversation_id, created_at)")
    op.execute("CREATE INDEX ix_messages_ws_client_msg ON messages (workspace_id, client_msg_id)")
    op.execute(
        "CREATE INDEX ix_messages_text_trgm ON messages USING gin (text_plain gin_trgm_ops)"
    )

    op.execute(
        """
        CREATE TABLE events (
            id UUID NOT NULL,
            workspace_id UUID NOT NULL,
            type VARCHAR(64) NOT NULL,
            occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            actor_type VARCHAR(16) NOT NULL DEFAULT 'system',
            actor_id UUID,
            conversation_id UUID,
            contact_id UUID,
            channel_type VARCHAR(24),
            channel_account_id UUID,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            published BOOLEAN NOT NULL DEFAULT false,
            PRIMARY KEY (id, occurred_at)
        ) PARTITION BY RANGE (occurred_at)
        """
    )
    op.execute("CREATE TABLE events_default PARTITION OF events DEFAULT")
    op.execute("CREATE INDEX ix_events_ws_occurred ON events (workspace_id, occurred_at)")
    op.execute("CREATE INDEX ix_events_type_occurred ON events (type, occurred_at)")
    op.execute("CREATE INDEX ix_events_unpublished ON events (published) WHERE NOT published")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS events CASCADE")
    op.execute("DROP TABLE IF EXISTS messages CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quick_replies_ws_scope', table_name='quick_replies')
    op.drop_table('quick_replies')
    op.drop_index(op.f('ix_conversation_tags_workspace_id'), table_name='conversation_tags')
    op.drop_table('conversation_tags')
    op.drop_index('ix_conversation_sessions_ws_started', table_name='conversation_sessions')
    op.drop_index('ix_conversation_sessions_ws_conv', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('ix_conversation_reads_ws_member', table_name='conversation_reads')
    op.drop_table('conversation_reads')
    op.drop_index('ix_conversation_assignments_ws_conv', table_name='conversation_assignments')
    op.drop_table('conversation_assignments')
    op.drop_index('ix_visitor_events_ws_occurred', table_name='visitor_events')
    op.drop_index('ix_visitor_events_ws_identity', table_name='visitor_events')
    op.drop_table('visitor_events')
    op.drop_index(op.f('ix_saved_views_workspace_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index(op.f('ix_quick_reply_folders_workspace_id'), table_name='quick_reply_folders')
    op.drop_table('quick_reply_folders')
    op.drop_index('ix_member_shifts_ws_member', table_name='member_shifts')
    op.drop_table('member_shifts')
    op.drop_index(op.f('ix_member_group_members_workspace_id'), table_name='member_group_members')
    op.drop_table('member_group_members')
    op.drop_table('member_daily_stats')
    op.drop_index(op.f('ix_materials_workspace_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index('ix_conversations_ws_status_last', table_name='conversations')
    op.drop_index('ix_conversations_ws_needs_reply', table_name='conversations')
    op.drop_index('ix_conversations_ws_contact', table_name='conversations')
    op.drop_index('ix_conversations_ws_assignee', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_contact_notes_ws_contact', table_name='contact_notes')
    op.drop_table('contact_notes')
    op.drop_index('ix_contact_merges_ws_target', table_name='contact_merges')
    op.drop_table('contact_merges')
    op.drop_index(op.f('ix_api_tokens_workspace_id'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index('uq_members_ws_user_notnull', table_name='workspace_members', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_widgets_workspace_id'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index('ix_webhook_deliveries_ws_sub', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_retry', table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_device_bridges_workspace_id'), table_name='device_bridges')
    op.drop_table('device_bridges')
    op.drop_index(op.f('ix_contact_tags_workspace_id'), table_name='contact_tags')
    op.drop_table('contact_tags')
    op.drop_index('ix_contact_orders_ws_contact', table_name='contact_orders')
    op.drop_table('contact_orders')
    op.drop_table('contact_merge_candidates')
    op.drop_index('ix_channel_identities_ws_contact', table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_logged_in_external_id'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_index(op.f('ix_webhook_subscriptions_workspace_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_table('usage_counters')
    op.drop_index('ix_timers_ws_kind_ref', table_name='timers')
    op.drop_index('ix_timers_status_fire', table_name='timers')
    op.drop_table('timers')
    op.drop_table('tags')
    op.drop_index(op.f('ix_subscriptions_workspace_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('roles')
    op.drop_index('ix_message_translations_ws', table_name='message_translations')
    op.drop_table('message_translations')
    op.drop_table('message_dedup')
    op.drop_table('member_groups')
    op.drop_table('mac_activity')
    op.drop_index(op.f('ix_llm_profiles_workspace_id'), table_name='llm_profiles')
    op.drop_table('llm_profiles')
    op.drop_table('files')
    op.drop_table('custom_field_definitions')
    op.drop_index('ix_contacts_ws_phone', table_name='contacts')
    op.drop_index('ix_contacts_ws_last_seen', table_name='contacts')
    op.drop_index('ix_contacts_ws_email', table_name='contacts')
    op.drop_index('ix_contacts_custom_gin', table_name='contacts', postgresql_using='gin')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_channel_accounts_workspace_id'), table_name='channel_accounts')
    op.drop_table('channel_accounts')
    op.drop_index('ix_audit_logs_ws_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_ai_points_ledger_ws_created', table_name='ai_points_ledger')
    op.drop_table('ai_points_ledger')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('translation_cache')
    op.drop_table('plans')
    # ### end Alembic commands ###
